site_name: FossWiki
site_url: https://lzccr.github.io/fosswiki
repo_url: https://github.com/lzccr/fosswiki
repo_name: lzccr/mkdocs-test
# edit_url: edit/main/docs
copyright: MIT License

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  features:
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.expand
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.code.copy
  #    - content.action.edit
  font:
    text: Poppins
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - privacy:
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
      log-level: error
      links_attr_map:
        target: _blank
  - search
  - social:
      cards_layout_options:
        font_family: Roboto
        background_color: green
        background_image: null
#    - git-revision-date-localized:
#        enable_creation_date: true
#        type: timeago
#        fallback_to_build_date: false
#   - git-committers:
#     repository: lzccr/mkdocs-tests
#     branch: main
#   - git-authors

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@lzccr
      name: lzccr on Fosstodon
    - icon: fontawesome/brands/github
      link: https://github.com/lzccr
      name: lzccr on Github
